# Handling missing data (dropna abd fillna) in python pandas

In [13]:
import pandas as pd

In [14]:
csv_1 = pd.read_csv("/home/jawad/Downloads/employees.csv")
csv_1

           Name   Department   Salary  Years_Experience
0   Alice Smith  Engineering  75000.0               5.0
1   Bob Johnson          NaN  68000.0               3.0
2     Carol Lee  Engineering  82000.0               NaN
3   David Brown        Sales      NaN               2.0
4     Eve Davis          NaN  71000.0               4.0
5  Frank Miller  Engineering  90000.0              10.0
6  Grace Wilson        Sales  48000.0               NaN

# droping nan values from the file

In [15]:
csv_1.dropna() # by default it drop only missing value rows
csv_1.dropna(axis=1) # it drop only the missing value columns
csv_1.dropna(axis=0) # it drop only the missing value rows
csv_1.dropna(how="any") # it drop the entire row in which all the values are nan

           Name   Department   Salary  Years_Experience
0   Alice Smith  Engineering  75000.0               5.0
5  Frank Miller  Engineering  90000.0              10.0

In [ ]:
# csv_1
csv_1.dropna(subset=["Department"]) # droping the data in a specific column just like here i drop the nan values of department columns only
# csv_1.dropna(subset=["Name"])  here is no nan value in the name columns

           Name   Department   Salary  Years_Experience
0   Alice Smith  Engineering  75000.0               5.0
1   Bob Johnson          NaN  68000.0               3.0
2     Carol Lee  Engineering  82000.0               NaN
3   David Brown        Sales      NaN               2.0
4     Eve Davis          NaN  71000.0               4.0
5  Frank Miller  Engineering  90000.0              10.0
6  Grace Wilson        Sales  48000.0               NaN

In [24]:
csv_1.dropna(thresh= 2)

           Name   Department   Salary  Years_Experience
0   Alice Smith  Engineering  75000.0               5.0
1   Bob Johnson          NaN  68000.0               3.0
2     Carol Lee  Engineering  82000.0               NaN
3   David Brown        Sales      NaN               2.0
4     Eve Davis          NaN  71000.0               4.0
5  Frank Miller  Engineering  90000.0              10.0
6  Grace Wilson        Sales  48000.0               NaN

# filling missing data

In [26]:
csv_1.fillna(1111.1111)

           Name   Department      Salary  Years_Experience
0   Alice Smith  Engineering  75000.0000            5.0000
1   Bob Johnson    1111.1111  68000.0000            3.0000
2     Carol Lee  Engineering  82000.0000         1111.1111
3   David Brown        Sales   1111.1111            2.0000
4     Eve Davis    1111.1111  71000.0000            4.0000
5  Frank Miller  Engineering  90000.0000           10.0000
6  Grace Wilson        Sales  48000.0000         1111.1111

# filling data within  a specfic columns

In [28]:
csv_1.fillna({"Department":"computer science","Salary":0.00000})

           Name        Department   Salary  Years_Experience
0   Alice Smith       Engineering  75000.0               5.0
1   Bob Johnson  computer science  68000.0               3.0
2     Carol Lee       Engineering  82000.0               NaN
3   David Brown             Sales      0.0               2.0
4     Eve Davis  computer science  71000.0               4.0
5  Frank Miller       Engineering  90000.0              10.0
6  Grace Wilson             Sales  48000.0               NaN

# filling nan values like forward and backword values in a columns

In [39]:
csv_1.ffill() # forward filling nan value filled with respect to the above the fill value
csv_1.bfill() # backword filling nan value filled with respect to the below the fill value

           Name   Department   Salary  Years_Experience
0   Alice Smith  Engineering  75000.0               5.0
1   Bob Johnson  Engineering  68000.0               3.0
2     Carol Lee  Engineering  82000.0               2.0
3   David Brown        Sales  71000.0               2.0
4     Eve Davis  Engineering  71000.0               4.0
5  Frank Miller  Engineering  90000.0              10.0
6  Grace Wilson        Sales  48000.0               NaN