# merging

In [2]:
import numpy as np
import pandas as pd

In [3]:
var_1 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,7,8]})
var_2 = pd.DataFrame({"a":[1,2,4,5],"d":[5,4,3,2]})
pd.merge(var_1,var_2,on="a")
 # how{‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’, ‘left_anti’, ‘right_anti’},

   a  b  d
0  1  5  5
1  2  6  4
2  5  8  2

In [4]:
var_3 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,7,8]})
var_4 = pd.DataFrame({"a":[1,2,4,5],"b":[5,4,3,2]})
pd.merge(var_3,var_4,left_index=True,right_index=True,suffixes=("jawad","ali"))

   ajawad  bjawad  aali  bali
0       1       5     1     5
1       2       6     2     4
2       3       7     4     3
3       5       8     5     2

# concat

In [5]:
ser_one = pd.Series([1,2,3,4,5])
ser_two = pd.Series([5,4,3,2,1])
pd.concat([ser_one,ser_two])

0    1
1    2
2    3
3    4
4    5
0    5
1    4
2    3
3    2
4    1
dtype: int64

In [ ]:
d1 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,7,8]})
d2= pd.DataFrame({"a":[1,2,4,5],"b":[5,4,3,2]})
pd.concat([d1,d2])

   a  b
0  1  5
1  2  6
2  3  7
3  5  8
0  1  5
1  2  4
2  4  3
3  5  2

In [9]:
d1 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,7,8]})
d2= pd.DataFrame({"a":[1,2,4,5],"b":[5,4,3,2]})
pd.concat([d1,d2],axis=1)

   a  b  a  b
0  1  5  1  5
1  2  6  2  4
2  3  7  4  3
3  5  8  5  2

In [17]:
d1 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,8,4]})
d2= pd.DataFrame({"a":[1,2,4],"b":[5,4,3]})
pd.concat([d1,d2],axis=1,keys=["d1"," d2"])

  d1      d2
   a  b    a    b
0  1  5  1.0  5.0
1  2  6  2.0  4.0
2  3  8  4.0  3.0
3  5  4  NaN  NaN

In [18]:
d1 = pd.DataFrame({"a":[1,2,3,5]})
d2= pd.DataFrame({"a":[1,2,4],"b":[5,4,3]})
pd.concat([d1,d2],axis=1)

   a    a    b
0  1  1.0  5.0
1  2  2.0  4.0
2  3  4.0  3.0
3  5  NaN  NaN