# Replaced and interpolate

In [1]:
import pandas as pd

In [4]:
file_var = pd.read_csv("/home/jawad/Downloads/employees.csv")

file_var

           Name   Department   Salary  Years_Experience
0   Alice Smith  Engineering  75000.0               5.0
1   Bob Johnson          NaN  68000.0               3.0
2     Carol Lee  Engineering  82000.0               NaN
3   David Brown        Sales      NaN               2.0
4     Eve Davis          NaN  71000.0               4.0
5  Frank Miller  Engineering  90000.0              10.0
6  Grace Wilson        Sales  48000.0               NaN

In [15]:
# to replace is ues to what replace with what value
file_var.replace(to_replace="Alice Smith",value="jawad ali")
# alice smith are replaced with jawad ali

           Name   Department   Salary  Years_Experience
0     jawad ali  Engineering  75000.0               5.0
1   Bob Johnson          NaN  68000.0               3.0
2     Carol Lee  Engineering  82000.0               NaN
3   David Brown        Sales      NaN               2.0
4     Eve Davis          NaN  71000.0               4.0
5  Frank Miller  Engineering  90000.0              10.0
6  Grace Wilson        Sales  48000.0               NaN

In [20]:
# years of experincing are replaced with 10
file_var.replace([0,1,2,3,4,5,6],10)

           Name   Department   Salary  Years_Experience
0   Alice Smith  Engineering  75000.0              10.0
1   Bob Johnson          NaN  68000.0              10.0
2     Carol Lee  Engineering  82000.0               NaN
3   David Brown        Sales      NaN              10.0
4     Eve Davis          NaN  71000.0              10.0
5  Frank Miller  Engineering  90000.0              10.0
6  Grace Wilson        Sales  48000.0               NaN

In [21]:
# alphabatic data in the file are replaced with the help of regex keyword
file_var.replace("[a-zA-Z]","PAKISTAN",regex=True)

,Name,Department,Salary,Years_Experience
0,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTAN PAKIS...,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTANPAKIST...,75000.0,5.0
1,PAKISTANPAKISTANPAKISTAN PAKISTANPAKISTANPAKIS...,NaN,68000.0,3.0
2,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTAN PAKIS...,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTANPAKIST...,82000.0,NaN
3,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTAN PAKIS...,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTAN,NaN,2.0
4,PAKISTANPAKISTANPAKISTAN PAKISTANPAKISTANPAKIS...,NaN,71000.0,4.0
5,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTAN PAKIS...,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTANPAKIST...,90000.0,10.0
6,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTAN PAKIS...,PAKISTANPAKISTANPAKISTANPAKISTANPAKISTAN,48000.0,NaN

In [25]:
# REPLACING DATA OF THE SPECFIC COLUMNS WITH THE HELP OF DICTIONARY
file_var.replace({"Name":"[A-Z]"},500,regex=True)

  Name   Department   Salary  Years_Experience
0  500  Engineering  75000.0               5.0
1  500          NaN  68000.0               3.0
2  500  Engineering  82000.0               NaN
3  500        Sales      NaN               2.0
4  500          NaN  71000.0               4.0
5  500  Engineering  90000.0              10.0
6  500        Sales  48000.0               NaN

In [31]:
file_var.ffill()

  Name   Department   Salary  Years_Experience
0  500  Engineering  75000.0               5.0
1  500  Engineering  68000.0               3.0
2  500  Engineering  82000.0               3.0
3  500        Sales  82000.0               2.0
4  500        Sales  71000.0               4.0
5  500  Engineering  90000.0              10.0
6  500        Sales  48000.0              10.0

In [36]:
file_var.fillna("jawad",limit=3)

  Name   Department   Salary Years_Experience
0  500  Engineering  75000.0              5.0
1  500        jawad  68000.0              3.0
2  500  Engineering  82000.0            jawad
3  500        Sales    jawad              2.0
4  500        jawad  71000.0              4.0
5  500  Engineering  90000.0             10.0
6  500        Sales  48000.0            jawad