# merging

In [54]:
import numpy as np
import pandas as pd

In [55]:
var_1 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,7,8]})
var_2 = pd.DataFrame({"a":[1,2,4,5],"d":[5,4,3,2]})
pd.merge(var_1,var_2,on="a")
 # how{‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’, ‘left_anti’, ‘right_anti’},

   a  b  d
0  1  5  5
1  2  6  4
2  5  8  2

In [56]:
var_3 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,7,8]})
var_4 = pd.DataFrame({"a":[1,2,4,5],"b":[5,4,3,2]})
pd.merge(var_3,var_4,left_index=True,right_index=True,suffixes=("jawad","ali"))

   ajawad  bjawad  aali  bali
0       1       5     1     5
1       2       6     2     4
2       3       7     4     3
3       5       8     5     2

# concat

In [57]:
ser_one = pd.Series([1,2,3,4,5])
ser_two = pd.Series([5,4,3,2,1])
pd.concat([ser_one,ser_two],ignore_index=True)

0    1
1    2
2    3
3    4
4    5
5    5
6    4
7    3
8    2
9    1
dtype: int64

In [58]:
d1 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,7,8]})
d2= pd.DataFrame({"a":[1,2,4,5],"b":[5,4,3,2]})
pd.concat([d1,d2])

   a  b
0  1  5
1  2  6
2  3  7
3  5  8
0  1  5
1  2  4
2  4  3
3  5  2

In [59]:
d1 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,7,8]})
d2= pd.DataFrame({"a":[1,2,4,5],"b":[5,4,3,2]})
pd.concat([d1,d2],axis=1)

   a  b  a  b
0  1  5  1  5
1  2  6  2  4
2  3  7  4  3
3  5  8  5  2

In [60]:
d1 = pd.DataFrame({"a":[1,2,3,5],"b":[5,6,8,4]})
d2= pd.DataFrame({"a":[1,2,4],"b":[5,4,3]})
pd.concat([d1,d2],axis=1,keys=["d1"," d2"])

  d1      d2
   a  b    a    b
0  1  5  1.0  5.0
1  2  6  2.0  4.0
2  3  8  4.0  3.0
3  5  4  NaN  NaN

In [61]:
d1 = pd.DataFrame({"a":[1,2,3,5]})
d2= pd.DataFrame({"a":[1,2,4],"b":[5,4,3]})
pd.concat([d1,d2],axis=1)

   a    a    b
0  1  1.0  5.0
1  2  2.0  4.0
2  3  4.0  3.0
3  5  NaN  NaN

# group by function

In [62]:
var = pd.DataFrame({"a":["a","b","c","c","a","a","b","c","b","b"],
                    "subj_one":[12,13,14,15,12,13,14,14,12,11],
                    "subj_two":[12,15,14,13,13,14,12,11,15,11]})
var
group = var.groupby("a")["subj_one"]
for x,y in group:
    print(x)
    print(y)

a
0    12
4    12
5    13
Name: subj_one, dtype: int64
b
1    13
6    14
8    12
9    11
Name: subj_one, dtype: int64
c
2    14
3    15
7    14
Name: subj_one, dtype: int64

In [63]:
group.get_group("a")
# TO GET ONLY THE VALUE OF A

0    12
4    12
5    13
Name: subj_one, dtype: int64

In [64]:
group.min()

a
a    12
b    11
c    14
Name: subj_one, dtype: int64

In [65]:
group.max()

a
a    13
b    14
c    15
Name: subj_one, dtype: int64

In [66]:
group.mean()

a
a    12.333333
b    12.500000
c    14.333333
Name: subj_one, dtype: float64

In [67]:
group.describe()

   count       mean       std   min    25%   50%    75%   max
a
a    3.0  12.333333  0.577350  12.0  12.00  12.0  12.50  13.0
b    4.0  12.500000  1.290994  11.0  11.75  12.5  13.25  14.0
c    3.0  14.333333  0.577350  14.0  14.00  14.0  14.50  15.0

NameError: name 'group' is not defined