###  Problem: Student Exam Scores Analysis
You are given data for 5 students with their exam scores in three subjects. Perform basic data manipulation and analysis using pandas.

In [124]:
import pandas as pd
import numpy as np

In [125]:
dict = {"student":["ali","sara","john","emma","raj"],"math":[85,92,67,95,74],"science":[90,88,72,93,68],"english":[78,84,70,89,81]}
dfr = pd.DataFrame(dict)
print(dfr)
# dfr["average"] = (dfr["math"] + dfr["science"] + dfr["english"])/3
dfr["average"]= dfr[["math","science","english"]].mean(axis=1)
dfr
dfr["result"] = np.where(dfr["average"] >= 70,"pass","fail")
dfr

  student  math  science  english
0     ali    85       90       78
1    sara    92       88       84
2    john    67       72       70
3    emma    95       93       89
4     raj    74       68       81

  student  math  science  english    average result
0     ali    85       90       78  84.333333   pass
1    sara    92       88       84  88.000000   pass
2    john    67       72       70  69.666667   fail
3    emma    95       93       89  92.333333   pass
4     raj    74       68       81  74.333333   pass

### Problem 1 — Create a Series

Create a pandas Series from this list:

In [126]:
data = [10, 20, 30, 40, 50]
var = pd.Series(data)
print(var)
print("ist element of the series : ",var[0])
print("the last element of the series : ",var[4])

0    10
1    20
2    30
3    40
4    50
dtype: int64
ist element of the series :  10
the last element of the series :  50

### Problem 2 — Create a DataFrame

In [127]:
dataa = {"name":["ali","sara","ahmed"],"age":[20,21,19],"marks":[85,90,78]}
varr = pd.DataFrame(dataa)
print("the whole data frame : \n",varr)

print("\n")

print(varr["name"])
print(varr.iloc[0])

the whole data frame :
     name  age  marks
0    ali   20     85
1   sara   21     90
2  ahmed   19     78


0      ali
1     sara
2    ahmed
Name: name, dtype: str
name     ali
age       20
marks     85
Name: 0, dtype: object

###  Problem 3 — Find Shape

Create a DataFrame with random integers of shape (5, 4).

Print:

number of rows
number of columns
full shape

In [128]:
dataframe = pd.DataFrame(np.random.randint(1,6,(5,4)))
print(dataframe)
#shape of the dataframe
print("shape of the dataframe : ",dataframe.shape)
print("rows in the dataframe : ",dataframe.shape[0])
print("columns in the dataframe : ",dataframe.shape[1])

   0  1  2  3
0  5  3  3  4
1  5  3  5  4
2  5  5  2  1
3  5  3  2  1
4  4  1  4  5
shape of the dataframe :  (5, 4)
rows in the dataframe :  5
columns in the dataframe :  4

### Problem 4 — Column Statistics

Create this DataFrame:

{
    "Math": [80, 90, 70, 60],
    "Physics": [75, 85, 95, 65]
}

Find:

mean
maximum value
minimum value

for each column.

In [129]:
dict = {
    "Math": [80, 90, 70, 60],
    "Physics": [75, 85, 95, 65]
}
dataframee = pd.DataFrame(dict)
print(dataframee)
mean = np.mean(dataframee[1:3],axis=0)
print("mean of the columms : \n",mean)
print("maximum value in columns:\n",np.max(dataframee,axis=0))
print("minimum value in columns:\n",np.min(dataframee,axis=0))



print("_________________________________________________")
print("PANDAS STYLE ")
print("_________________________________________________")
print(dataframee.mean(axis=0))
print(dataframee.max(axis=0))
print(dataframee.min(axis=0))

   Math  Physics
0    80       75
1    90       85
2    70       95
3    60       65
mean of the columms :
 Math       80.0
Physics    90.0
dtype: float64
maximum value in columns:
 Math       90
Physics    95
dtype: int64
minimum value in columns:
 Math       60
Physics    65
dtype: int64
_________________________________________________
PANDAS STYLE
_________________________________________________
Math       75.0
Physics    80.0
dtype: float64
Math       90
Physics    95
dtype: int64
Math       60
Physics    65
dtype: int64

### Problem 5 — Filter Rows

rint only students whose marks are greater than 50.

In [130]:
student_data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha"],
    "Marks": [45, 80, 65, 30]
}
dfr = pd.DataFrame(student_data)
filterr = dfr[dfr["Marks"] > 50 ]
filterr

    Name  Marks
1   Sara     80
2  Ahmed     65

### You are given a small dataset of students and their scores. Perform the following tasks to practice adding and removing data.

In [137]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [88, 81, 95]
})
# adding new column
df.insert(3,"English",[90,84,88])


# calculating sum of the subjects
df.insert(4,"total",df[['Math','English']].sum(axis=1))

# adding a new row
new_row = pd.DataFrame([['Diana', 89, 93, 91,89+93+91]], columns=df.columns)
df = pd.concat([df, new_row], ignore_index=True)
print("before deletion data frame : \n\n\n",df)

# deleting the science columns
df.pop("Science")


# deleting the bob rows here we use inplace = true it modifies the orignal dataframe instead of returning a new dataframe
df.drop(index=1,inplace=True)


# reset index
df.reset_index(drop=True,inplace=True)
print('n\n\n\n')
print("Original DataFrame:")
print(df)

before deletion data frame :


       Name  Math  Science  English  total
0    Alice    85       88       90    175
1      Bob    78       81       84    162
2  Charlie    92       95       88    180
3    Diana    89       93       91    273
n



Original DataFrame:
      Name  Math  English  total
0    Alice    85       90    175
1  Charlie    92       88    180
2    Diana    89       91    273