# medium levle problems in pandas

In [2]:

import pandas as pd
import numpy as np

data = {
    "Name": ["Ali", "Sara", "John", "Ayesha", "David", "Hina", "Ahmed"],
    "Math": [78, 92, 65, 88, 90, 95, 72],
    "Physics": [85, 91, 70, 60, 89, 98, 75],
    "Attendance": [90, 96, 70, 85, 88, 99, 80],
    "Department": ["CS", "IT", "CS", "SE", "IT", "CS", "SE"]
}

df = pd.DataFrame(data)
# Show students who belong to "CS" department and math marks are less than 75
cs_Std = df.loc[(df["Department"] == "CS") & (df["Math"] < 75 ) ]
print(cs_Std)
print("----------------------------------------------")
# Show students who Attendance is less than 85  OR Physics marks are less than 72
filter_std = df.loc[(df["Attendance"] < 85 ) | (df["Physics"] <72)]
print("students who Attendance is less than 85  OR Physics marks are less than 72\n",filter_std)
print("----------------------------------------------")
# Show students who are NOT from "IT" department
not_it_std = df.loc[df["Department"] != "IT"]
print("student not from IT department : \n",not_it_std)
print("----------------------------------------------")
# Show students whose Math marks are between 70 and 90
math_70_90 = df.loc[(df["Math"] > 70 )& (df["Math"] < 90)]
print("student whoes marks between 70 and 90 \n",math_70_90)
print("----------------------------------------------")

# show name ,math,department
result = df.loc[df["Attendance"] > 85 ,["Name","Math","Department"]]
print(result)
print("----------------------------------------------")
# Sort only CS students by Math marks in descending order.
sort = df[df["Department"]== "CS"].sort_values(by="Math",ascending=False ) 
print(sort)

df

   Name  Math  Physics  Attendance Department
2  John    65       70          70         CS
----------------------------------------------
students who Attendance is less than 85  OR Physics marks are less than 72
      Name  Math  Physics  Attendance Department
2    John    65       70          70         CS
3  Ayesha    88       60          85         SE
6   Ahmed    72       75          80         SE
----------------------------------------------
student not from IT department :
      Name  Math  Physics  Attendance Department
0     Ali    78       85          90         CS
2    John    65       70          70         CS
3  Ayesha    88       60          85         SE
5    Hina    95       98          99         CS
6   Ahmed    72       75          80         SE
----------------------------------------------
student whoes marks between 70 and 90
      Name  Math  Physics  Attendance Department
0     Ali    78       85          90         CS
3  Ayesha    88       60          85         SE
6   Ahmed    72       75          80         SE
----------------------------------------------
    Name  Math Department
0    Ali    78         CS
1   Sara    92         IT
4  David    90         IT
5   Hina    95         CS
----------------------------------------------
   Name  Math  Physics  Attendance Department
5  Hina    95       98          99         CS
0   Ali    78       85          90         CS
2  John    65       70          70         CS

     Name  Math  Physics  Attendance Department
0     Ali    78       85          90         CS
1    Sara    92       91          96         IT
2    John    65       70          70         CS
3  Ayesha    88       60          85         SE
4   David    90       89          88         IT
5    Hina    95       98          99         CS
6   Ahmed    72       75          80         SE


# Sample Data Creation (run this first)
1. Basic Filtering
Task: Filter the DataFrame to show only employees in the IT department who earn more than $75,000.

In [3]:


# Employee dataset
np.random.seed(42)
df = pd.DataFrame({
    'employee_id': range(101, 111),
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace', 'Hank', 'Ivy', 'Jack'],
    'department': ['Sales', 'IT', 'Sales', 'HR', 'IT', 'Sales', 'HR', 'IT', 'Marketing', 'Marketing'],
    'salary': [55000, 72000, 58000, 51000, 81000, 54000, 53000, 79000, 62000, 61000],
    'experience_years': [5, 8, 3, 4, 10, 2, 6, 9, 7, 5],
    'bonus': [2000, 3500, 2500, 1800, 4000, 2200, 2100, 3900, 3000, 2800],
    'city': ['NYC', 'SF', 'NYC', 'Austin', 'SF', 'NYC', 'Austin', 'SF', 'Seattle', 'Seattle']
    
})

#Task: Filter the DataFrame to show only employees in the IT department who earn more than $75,000.
filter = df[(df["department"] == "IT"  ) & (df["salary"] > 75000)]
print(filter)
print("\n\n\n")
# Task: Find the average salary and total bonus for each department.
result = pd.DataFrame({"average_sal":df.groupby("department")["salary"].mean(),
"total_bouns ": df.groupby("department")["bonus"].sum()})
print(result)

df

   employee_id  name department  salary  experience_years  bonus city
4          105   Eve         IT   81000                10   4000   SF
7          108  Hank         IT   79000                 9   3900   SF




             average_sal  total_bouns
department
HR          52000.000000          3900
IT          77333.333333         11400
Marketing   61500.000000          5800
Sales       55666.666667          6700

   employee_id     name department  salary  experience_years  bonus     city
0          101    Alice      Sales   55000                 5   2000      NYC
1          102      Bob         IT   72000                 8   3500       SF
2          103  Charlie      Sales   58000                 3   2500      NYC
3          104    Diana         HR   51000                 4   1800   Austin
4          105      Eve         IT   81000                10   4000       SF
5          106    Frank      Sales   54000                 2   2200      NYC
6          107    Grace         HR   53000                 6   2100   Austin
7          108     Hank         IT   79000                 9   3900       SF
8          109      Ivy  Marketing   62000                 7   3000  Seattle
9          110     Jack  Marketing   61000                 5   2800  Seattle

Display the first 5 rows.
Find the number of missing values in each column.
Replace missing Price values with the mean Price.
Replace missing Quantity values with the median Quantity.
Replace missing Rating values with the average Rating.
Create a new column Total_Sales = Price × Quantity.
Find the product with the highest Total_Sales.
Calculate the total sales for each Category.
Find the average Rating for each Product.
Sort the DataFrame by Total_Sales in descending order.
Display only rows where Rating > 4.3.
Find the top 3 products by total sales.
Calculate the percentage contribution of each row to the overall sales.
Create a new column:
"Excellent" if Rating ≥ 4.5
"Good" if Rating ≥ 4.0 and < 4.5
"Average" otherwise

In [4]:

data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Laptop",
                "Mouse", "Keyboard", "Monitor", "Laptop", "Mouse"],
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics",
                 "Electronics", "Accessories", "Accessories", "Electronics",
                 "Electronics", "Accessories"],
    "Price": [80000, 1500, 3000, 25000, 82000, np.nan, 3200, 26000, 79000, 1800],
    "Quantity": [5, 20, 10, 4, 3, 15, np.nan, 6, 2, 18],
    "Rating": [4.5, 4.2, 4.0, np.nan, 4.7, 4.1, 3.9, 4.4, 4.8, 4.3]
}

df = pd.DataFrame(data)
# Display the first 5 rows.
df.head(5)
# Find the number of missing values in each column.
df.isnull().sum()
# Replace missing Price values with the mean Price.
mean = df["Price"].mean()
df["Price"]= df["Price"].fillna(mean)
# Replace missing Quantity values with the median Quantity.
median = df["Quantity"].median()
df["Quantity"] = df["Quantity"].fillna(median)
# Replace missing Rating values with the average Rating.
avg_rat = df["Rating"].mean()
df["Rating"] = df["Rating"].fillna(avg_rat)
# Create a new column Total_Sales = Price × Quantity.
df["total_Sales"] =df["Price"] * df["Quantity"]
# Find the product with the highest Total_Sales.
highest_sales = df.loc[df["total_Sales"].idxmax()]
print("highest_sales product : \n",highest_sales)
print("\n")
# Calculate the total sales for each Category.
category_sales = df.groupby("Category")["total_Sales"].sum()
print(category_sales)
print("\n")
# Find the average Rating for each Product.
average_rat = df.groupby("Product")["Rating"].mean()
print(average_rat)
print("\n\n")
# Sort the DataFrame by Total_Sales in descending order.
sort = df.sort_values(by="total_Sales",ascending=False)
print(sort)
# Display only rows where Rating > 4.3
filter = df.loc[np.where(df["Rating"] > 4.3)]
print(filter)
# Find the top 3 products by total sales.
top_3 = df.sort_values(by="total_Sales",ascending=False).head()
print(top_3)

df

highest_sales product :
 Product              Mouse
Category       Accessories
Price              33500.0
Quantity              15.0
Rating                 4.1
total_Sales       502500.0
Name: 5, dtype: object


Category
Accessories     614100.0
Electronics    1060000.0
Name: total_Sales, dtype: float64


Product
Keyboard    3.950000
Laptop      4.666667
Monitor     4.361111
Mouse       4.200000
Name: Rating, dtype: float64



    Product     Category    Price  Quantity    Rating  total_Sales
5     Mouse  Accessories  33500.0      15.0  4.100000     502500.0
0    Laptop  Electronics  80000.0       5.0  4.500000     400000.0
4    Laptop  Electronics  82000.0       3.0  4.700000     246000.0
8    Laptop  Electronics  79000.0       2.0  4.800000     158000.0
7   Monitor  Electronics  26000.0       6.0  4.400000     156000.0
3   Monitor  Electronics  25000.0       4.0  4.322222     100000.0
9     Mouse  Accessories   1800.0      18.0  4.300000      32400.0
1     Mouse  Accessories   1500.0      20.0  4.200000      30000.0
2  Keyboard  Accessories   3000.0      10.0  4.000000      30000.0
6  Keyboard  Accessories   3200.0       6.0  3.900000      19200.0
   Product     Category    Price  Quantity    Rating  total_Sales
0   Laptop  Electronics  80000.0       5.0  4.500000     400000.0
3  Monitor  Electronics  25000.0       4.0  4.322222     100000.0
4   Laptop  Electronics  82000.0       3.0  4.700000     246000.0
7  Monitor  Electronics  26000.0       6.0  4.400000     156000.0
8   Laptop  Electronics  79000.0       2.0  4.800000     158000.0
   Product     Category    Price  Quantity  Rating  total_Sales
5    Mouse  Accessories  33500.0      15.0     4.1     502500.0
0   Laptop  Electronics  80000.0       5.0     4.5     400000.0
4   Laptop  Electronics  82000.0       3.0     4.7     246000.0
8   Laptop  Electronics  79000.0       2.0     4.8     158000.0
7  Monitor  Electronics  26000.0       6.0     4.4     156000.0

    Product     Category    Price  Quantity    Rating  total_Sales
0    Laptop  Electronics  80000.0       5.0  4.500000     400000.0
1     Mouse  Accessories   1500.0      20.0  4.200000      30000.0
2  Keyboard  Accessories   3000.0      10.0  4.000000      30000.0
3   Monitor  Electronics  25000.0       4.0  4.322222     100000.0
4    Laptop  Electronics  82000.0       3.0  4.700000     246000.0
5     Mouse  Accessories  33500.0      15.0  4.100000     502500.0
6  Keyboard  Accessories   3200.0       6.0  3.900000      19200.0
7   Monitor  Electronics  26000.0       6.0  4.400000     156000.0
8    Laptop  Electronics  79000.0       2.0  4.800000     158000.0
9     Mouse  Accessories   1800.0      18.0  4.300000      32400.0

# merging and concat problems

In [5]:


# Sales data for Q1 and Q2
q1_sales = pd.DataFrame({
    'product': ['A', 'B', 'C'],
    'revenue': [1000, 1500, 800],
    'quantity': [10, 15, 8]
})

q2_sales = pd.DataFrame({
    'product': ['A', 'B', 'D'],
    'revenue': [1200, 1400, 900],
    'quantity': [12, 14, 9]
})

# Task: Concatenate Q1 and Q2 sales data
# Question: What happens to the indices when you concatenate?
# answer : indices are remain not changing 0 twice and 1 twice like thiss
# Expected output: All rows combined
pd.concat([q1_sales,q2_sales],ignore_index=True)

  product  revenue  quantity
0       A     1000        10
1       B     1500        15
2       C      800         8
3       A     1200        12
4       B     1400        14
5       D      900         9

In [6]:
# Different columns in each DataFrame
df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'id': [4, 5],
    'age': [25, 30],
    'city': ['NYC', 'LA']
})

# Task 1: Concatenate with default behavior (columns don't match)
# Task 2: Concatenate and fill missing values with 0
pd.concat([df1,df2]).fillna(0)

   id     name   age city
0   1    Alice   0.0    0
1   2      Bob   0.0    0
2   3  Charlie   0.0    0
0   4        0  25.0  NYC
1   5        0  30.0   LA

In [7]:
# Sales and product info
sales = pd.DataFrame({
    'sale_id': [101, 102, 103],
    'amount': [500, 600, 550]
})

product_info = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Keyboard'],
    'category': ['Electronics', 'Accessories', 'Accessories']
})

# Task: Concatenate horizontally (axis=1)
# Question: What assumption does this make about row alignment?
pd.concat([sales,product_info],axis=1,ignore_index=True)

     0    1         2            3
0  101  500    Laptop  Electronics
1  102  600     Mouse  Accessories
2  103  550  Keyboard  Accessories

# Tasks:

Group by Department.<br>
Find the average salary of each department.<br>
Find the maximum salary in each department.

In [17]:


df = pd.DataFrame({
    "Employee": ["Ali", "Sara", "John", "Ayesha", "Ahmed"],
    "Department": ["IT", "HR", "IT", "HR", "IT"],
    "Salary": [50000, 45000, 60000, 48000, 55000]
})
avg_salary = df.groupby("Department")["Salary"].mean()
max_salary=df.groupby("Department")["Salary"].max()
print("average salary of the departments : ",avg_salary)
print("maximum salary in the departments : ", max_salary)

average salary of the departments :  Department
HR    46500.0
IT    55000.0
Name: Salary, dtype: float64
maximum salary in the departments :  Department
HR    48000
IT    60000
Name: Salary, dtype: int64

# Tasks:

Group by Product.<br>
Find total sales for each product.<br>
Find average sales for each product.

In [21]:
df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse"],
    "Sales": [5, 10, 3, 8, 6]
})
total_sales = df.groupby("Product")["Sales"].sum()
avg_sales = df.groupby("Product")["Sales"].mean()

print("total sales for each product : ",total_sales )
print("average sales for each product : ",avg_sales)

total sales for each product :  Product
Keyboard     8
Laptop       8
Mouse       16
Name: Sales, dtype: int64
average sales for each product :  Product
Keyboard    8.0
Laptop      4.0
Mouse       8.0
Name: Sales, dtype: float64

# Tasks:

Find average marks by class.<br>
Find highest marks in each class.<br>
Count students in each class.

In [26]:
df = pd.DataFrame({
    "Student": ["Ali", "Sara", "John", "Ayesha", "Ahmed", "Hina"],
    "Class": ["A", "A", "B", "B", "A", "B"],
    "Marks": [78, 92, 65, 88, 70, 95]
})
print(df.groupby("Class")["Marks"].mean())
print(df.groupby("Class")["Marks"].max())
print(df.groupby("Class")["Student"].count())

Class
A    80.000000
B    82.666667
Name: Marks, dtype: float64
Class
A    92
B    95
Name: Marks, dtype: int64
Class
A    3
B    3
Name: Student, dtype: int64