# medium levle problems in pandas

In [6]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Ayesha", "David", "Hina", "Ahmed"],
    "Math": [78, 92, 65, 88, 90, 95, 72],
    "Physics": [85, 91, 70, 60, 89, 98, 75],
    "Attendance": [90, 96, 70, 85, 88, 99, 80],
    "Department": ["CS", "IT", "CS", "SE", "IT", "CS", "SE"]
}

df = pd.DataFrame(data)
# Show students who belong to "CS" department and math marks are less than 75
cs_Std = df.loc[(df["Department"] == "CS") & (df["Math"] < 75 ) ]
print(cs_Std)
print("----------------------------------------------")
# Show students who Attendance is less than 85  OR Physics marks are less than 72
filter_std = df.loc[(df["Attendance"] < 85 ) | (df["Physics"] <72)]
print("students who Attendance is less than 85  OR Physics marks are less than 72\n",filter_std)
print("----------------------------------------------")
# Show students who are NOT from "IT" department
not_it_std = df.loc[df["Department"] != "IT"]
print("student not from IT department : \n",not_it_std)
print("----------------------------------------------")
# Show students whose Math marks are between 70 and 90
math_70_90 = df.loc[(df["Math"] > 70 )& (df["Math"] < 90)]
print("student whoes marks between 70 and 90 \n",math_70_90)
print("----------------------------------------------")

# show name ,math,department
result = df.loc[df["Attendance"] > 85 ,["Name","Math","Department"]]
print(result)
print("----------------------------------------------")
# Sort only CS students by Math marks in descending order.
sort = df[df["Department"]== "CS"].sort_values(by="Math",ascending=False ) 
print(sort)

df

   Name  Math  Physics  Attendance Department
2  John    65       70          70         CS
----------------------------------------------
students who Attendance is less than 85  OR Physics marks are less than 72
      Name  Math  Physics  Attendance Department
2    John    65       70          70         CS
3  Ayesha    88       60          85         SE
6   Ahmed    72       75          80         SE
----------------------------------------------
student not from IT department :
      Name  Math  Physics  Attendance Department
0     Ali    78       85          90         CS
2    John    65       70          70         CS
3  Ayesha    88       60          85         SE
5    Hina    95       98          99         CS
6   Ahmed    72       75          80         SE
----------------------------------------------
student whoes marks between 70 and 90
      Name  Math  Physics  Attendance Department
0     Ali    78       85          90         CS
3  Ayesha    88       60          85         SE
6   Ahmed    72       75          80         SE
----------------------------------------------
    Name  Math Department
0    Ali    78         CS
1   Sara    92         IT
4  David    90         IT
5   Hina    95         CS
----------------------------------------------
   Name  Math  Physics  Attendance Department
5  Hina    95       98          99         CS
0   Ali    78       85          90         CS
2  John    65       70          70         CS

     Name  Math  Physics  Attendance Department
0     Ali    78       85          90         CS
1    Sara    92       91          96         IT
2    John    65       70          70         CS
3  Ayesha    88       60          85         SE
4   David    90       89          88         IT
5    Hina    95       98          99         CS
6   Ahmed    72       75          80         SE

In [10]:


dff = pd.DataFrame({
    "Name": ["Ali", "Sara", "John", "Ali"],
    "City": ["Lahore", "NaN", "Karachi", "NaN"]
})

dff = dff.replace("nan","unknown")
dff

   Name     City
0   Ali   Lahore
1  Sara      NaN
2  John  Karachi
3   Ali      NaN

In [ ]:
df = pd.DataFrame({
    "Grade": ["A", "B", "C", "A", "B"]
})
print(df.replace({"A":"excellent","B":"Good","C":"average"}))

       Grade
0  excellent
1       Good
2    average
3  excellent
4       Good

In [15]:
df = pd.DataFrame({
    "Marks": [100, -1, 85, -1, 90]
})
print(df.replace(-1,"nan"))

  Marks
0   100
1   nan
2    85
3   nan
4    90

In [16]:
df = pd.DataFrame({
    "Status": ["Y", "N", "Y", "N"]
})
dict = df.replace({"Y":"yes","N":"no"})
print(dict)

  Status
0    yes
1     no
2    yes
3     no