# Problem: Export Employee Data to CSV
You are given a dictionary containing employee records. Your task is to:

Create a pandas DataFrame from the data.

Save the DataFrame to a CSV file named employees.csv with the following requirements:

Exclude the index column from the CSV.

Use a semicolon (;) as the delimiter instead of comma.

Do not include the column headers in the output file.

Only save rows where Salary is greater than 50,000 (filter before saving).

In [2]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Department': ['HR', 'IT', 'IT', 'Marketing', 'HR'],
    'Salary': [55000, 72000, 48000, 91000, 46000],
    'Years_Exp': [3, 5, 2, 8, 1]
}
data_f = pd.DataFrame(data)
data_f.to_csv("employees.csv",index=False,sep=";",header=False)
data_f[data_f['Salary'] > 50000]
data_f

      Name Department  Salary  Years_Exp
0    Alice         HR   55000          3
1      Bob         IT   72000          5
2  Charlie         IT   48000          2
3    Diana  Marketing   91000          8
4      Eve         HR   46000          1

# reading a csv file

In [3]:
df = pd.read_csv("/home/jawad/Downloads/employees.csv")
print(df)
print("\n\n\n")
# ist three rows
print(df.head(3))
print("\n\n\n")
# information about the csv file 
print(df.info())
print("\n\n\n")

# calculate the average salary of the employee
print("average salary of the emplyee " ,df["Salary"].mean())
print("\n\n\n")
# filter and display only the employees from the engineering department
print(df[df['Department'] == "Engineering"])
print("\n\n\n")
# highest salar in the employee
max_salary = df['Salary'].max()
print(max_salary)
print("\n\n\n")
df["Bonus"] = df["Salary" ] *0.1
print(df)
df.to_csv("employees_with_bonus.csv",index=False)

           Name   Department  Salary  Years_Experience
0   Alice Smith  Engineering   75000                 5
1   Bob Johnson    Marketing   68000                 3
2     Carol Lee  Engineering   82000                 7
3   David Brown        Sales   55000                 2
4     Eve Davis    Marketing   71000                 4
5  Frank Miller  Engineering   90000                10
6  Grace Wilson        Sales   48000                 1




          Name   Department  Salary  Years_Experience
0  Alice Smith  Engineering   75000                 5
1  Bob Johnson    Marketing   68000                 3
2    Carol Lee  Engineering   82000                 7




<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              7 non-null      str
 1   Department        7 non-null      str
 2   Salary            7 non-null      int64
 3   Years_Experience  7 non-null      int64
dtypes: int64(2), str(2)
memory usage: 356.0 bytes
None




average salary of the emplyee  69857.14285714286




           Name   Department  Salary  Years_Experience
0   Alice Smith  Engineering   75000                 5
2     Carol Lee  Engineering   82000                 7
5  Frank Miller  Engineering   90000                10




90000




           Name   Department  Salary  Years_Experience   Bonus
0   Alice Smith  Engineering   75000                 5  7500.0
1   Bob Johnson    Marketing   68000                 3  6800.0
2     Carol Lee  Engineering   82000                 7  8200.0
3   David Brown        Sales   55000                 2  5500.0
4     Eve Davis    Marketing   71000                 4  7100.0
5  Frank Miller  Engineering   90000                10  9000.0
6  Grace Wilson        Sales   48000                 1  4800.0

# student performance analysis

### 1. Create a new column called "Average"

Calculate the average marks of each student.

In [4]:


data = {
    "Name": ["Ali", "Sara", "John", "Ayesha", "David", "Zain"],
    "Math": [78, 92, 85, 60, 88, 73],
    "Physics": [80, 95, 78, 65, 90, 70],
    "Chemistry": [75, 91, 82, 70, 85, 68]
}

df = pd.DataFrame(data)
df
df["average"] = df[["Math","Physics","Chemistry"]].mean(axis=1)
df

     Name  Math  Physics  Chemistry    average
0     Ali    78       80         75  77.666667
1    Sara    92       95         91  92.666667
2    John    85       78         82  81.666667
3  Ayesha    60       65         70  65.000000
4   David    88       90         85  87.666667
5    Zain    73       70         68  70.333333

### 2. Create a new column called "Result"

If average marks are greater than or equal to 75 → "Pass"
Otherwise → "Fail"

In [5]:
df["result"] = np.where(df["average"] >= 75 ,"pass","fail")
df

     Name  Math  Physics  Chemistry    average result
0     Ali    78       80         75  77.666667   pass
1    Sara    92       95         91  92.666667   pass
2    John    85       78         82  81.666667   pass
3  Ayesha    60       65         70  65.000000   fail
4   David    88       90         85  87.666667   pass
5    Zain    73       70         68  70.333333   fail

### Find the student with the highest average marks.

In [6]:
df.loc[df["average"].idxmax()]

Name              Sara
Math                92
Physics             95
Chemistry           91
average      92.666667
result            pass
Name: 1, dtype: object

In [7]:


np.random.seed(10)

data = {
    "Product": ["Laptop", "Phone", "Tablet", "Monitor", "Keyboard", "Mouse"],
    "Price": np.random.randint(500, 5000, 6),
    "Quantity": np.random.randint(1, 15, 6),
    "Discount": np.random.randint(5, 30, 6)
}

df = pd.DataFrame(data)

print(df)

    Product  Price  Quantity  Discount
0    Laptop   1789        14        15
1     Phone   1844         2        13
2    Tablet   3941        11        27
3   Monitor   1680         9         9
4  Keyboard   2509        10        24
5     Mouse   2020         1        21

# Create a new column:

In [10]:
df["total"] = df["Price"] * df["Quantity"]
df

    Product  Price  Quantity  Discount  total
0    Laptop   1789        14        15  25046
1     Phone   1844         2        13   3688
2    Tablet   3941        11        27  43351
3   Monitor   1680         9         9  15120
4  Keyboard   2509        10        24  25090
5     Mouse   2020         1        21   2020

In [12]:
df["final_price"] = df["total"] - ((df["total"] * df["Discount"])/100)
df

    Product  Price  Quantity  Discount  total  final_price
0    Laptop   1789        14        15  25046     21289.10
1     Phone   1844         2        13   3688      3208.56
2    Tablet   3941        11        27  43351     31646.23
3   Monitor   1680         9         9  15120     13759.20
4  Keyboard   2509        10        24  25090     19068.40
5     Mouse   2020         1        21   2020      1595.80

# 3.

Find:

Product with highest Final_Price
Product with lowest Final_Price

In [26]:
# product with highest final price
print(df.loc[df["final_price"].idxmax()])
print("\n\n")
# product with lowest final price
print(df.loc[df["final_price"].idxmin()])

Product          Tablet
Price              3941
Quantity             11
Discount             27
total             43351
final_price    31646.23
Name: 2, dtype: object



Product         Mouse
Price            2020
Quantity            1
Discount           21
total            2020
final_price    1595.8
Name: 5, dtype: object

In [37]:
df["final_price greater then 200000"] = df["final_price"]  > 20000
df

,Product,Price,Quantity,Discount,total,final_price,final_price greater then 200000
0,Laptop,1789,14,15,25046,21289.10,True
1,Phone,1844,2,13,3688,3208.56,False
2,Tablet,3941,11,27,43351,31646.23,True
3,Monitor,1680,9,9,15120,13759.20,False
4,Keyboard,2509,10,24,25090,19068.40,False
5,Mouse,2020,1,21,2020,1595.80,False

# 5.

Sort the DataFrame by Final_Price in descending order.

In [52]:
df.sort_values(by=["final_price"],ascending=False)

,Product,Price,Quantity,Discount,total,final_price,final_price greater then 200000
2,Tablet,3941,11,27,43351,31646.23,True
0,Laptop,1789,14,15,25046,21289.10,True
4,Keyboard,2509,10,24,25090,19068.40,False
3,Monitor,1680,9,9,15120,13759.20,False
1,Phone,1844,2,13,3688,3208.56,False
5,Mouse,2020,1,21,2020,1595.80,False